options:
  base-player-health: 20.0
core-stats:
  health:
    format: "%value% Health"
  damage:
    format: "%value% Damage"
  melee-damage:
    format: "%value% Melee Damage"
  ranged-damage:
    format: "%value% Ranged Damage"
  regeneration:
    format: "%value% Regeneration"
  armor:
    format: "%value% Armor"
  critical-rate:
    format: "%value% Critical Rate"
  critical-damage:
    format: "%value% Critical Damage"
  level-requirement:
    format: "Level Required: %value%"
  fire-immunity:
    format: "Fire Immunity"
  poison-immunity:
    format: "Poison Immunity"
  wither-immunity:
    format: "Wither Immunity"
version: "1.0.3"