version: 1.0.12
options:
  base-player-health: 20.0
  base-critical-rate: 0.05
  base-critical-damage: 0.2
  base-stun-rate: 0.05
  base-stun-length: 1
  seconds-between-health-updates: 10
core-stats:
  poison-immunity:
    enabled: true
    format: Poison Immunity
    percentage: false
    max-value: -1.0
  ranged-damage:
    enabled: true
    format: '%value% Ranged Damage'
    percentage: false
    max-value: 100.0
  regeneration:
    enabled: true
    format: '%value% Regeneration'
    percentage: false
    max-value: 100.0
  critical-rate:
    enabled: true
    format: '%value% Critical Rate'
    percentage: true
    max-value: 100.0
  melee-damage:
    enabled: true
    format: '%value% Melee Damage'
    percentage: false
    max-value: 100.0
  fire-immunity:
    enabled: true
    format: Fire Immunity
    percentage: false
    max-value: -1.0
  health:
    enabled: true
    format: '%value% Health'
    percentage: false
    max-value: 100.0
  dodge-rate:
    enabled: true
    format: '%value% Dodge Rate'
    percentage: true
    max-value: 100.0
  armor:
    enabled: true
    format: '%value% Armor'
    percentage: false
    max-value: 100.0
  critical-damage:
    enabled: true
    format: '%value% Critical Damage'
    percentage: true
    max-value: 100.0
  stun-rate:
    enabled: true
    format: '%value% Stun Rate'
    percentage: true
    max-value: 100.0
  armor-penetration:
    enabled: true
    format: '%value% Armor Penetration'
    percentage: false
    max-value: 100.0
  level-requirement:
    enabled: true
    format: 'Level Requirement: %value%'
    percentage: false
    max-value: 100.0
  stun-length:
    enabled: true
    format: '%value% Stun Length'
    percentage: false
    max-value: 100.0
  wither-immunity:
    enabled: true
    format: Wither Immunity
    percentage: false
    max-value: -1.0