version: 1.0.20
options:
  seconds-between-health-updates: 10
  item-only-damage-system:
    enabled: false
    base-damage: 1.0
core-stats:
  attack-speed:
    enabled: true
    format: '%value% Attack Speed'
    percentage: true
    players-max-value: 100.0
    mobs-max-value: 100.0
    players-base-value: 1.0
    mobs-base-value: -1.0
    affects-mobs: false
    affects-players: true
    effect: MOBSPAWNER_FLAMES
    sound: BURP
  poison-immunity:
    enabled: true
    format: Poison Immunity
    percentage: false
    players-max-value: -1.0
    mobs-max-value: -1.0
    players-base-value: -1.0
    mobs-base-value: -1.0
    affects-mobs: true
    affects-players: true
  ranged-damage:
    enabled: true
    format: '%value% Ranged Damage'
    percentage: false
    players-max-value: 100.0
    mobs-max-value: 100.0
    players-base-value: 0.0
    mobs-base-value: 0.0
    affects-mobs: true
    affects-players: true
  regeneration:
    enabled: true
    format: '%value% Regeneration'
    percentage: false
    players-max-value: 100.0
    mobs-max-value: 100.0
    players-base-value: 0.0
    mobs-base-value: 0.0
    affects-mobs: true
    affects-players: true
  critical-rate:
    enabled: true
    format: '%value% Critical Rate'
    percentage: true
    players-max-value: 100.0
    mobs-max-value: 100.0
    players-base-value: 0.05
    mobs-base-value: 0.0
    affects-mobs: true
    affects-players: true
  melee-damage:
    enabled: true
    format: '%value% Melee Damage'
    percentage: false
    players-max-value: 100.0
    mobs-max-value: 100.0
    players-base-value: 0.0
    mobs-base-value: 0.0
    affects-mobs: true
    affects-players: true
  fire-immunity:
    enabled: true
    format: Fire Immunity
    percentage: false
    players-max-value: -1.0
    mobs-max-value: -1.0
    players-base-value: -1.0
    mobs-base-value: -1.0
    affects-mobs: true
    affects-players: true
  dodge-rate:
    enabled: true
    format: '%value% Dodge Rate'
    percentage: true
    players-max-value: 100.0
    mobs-max-value: 100.0
    players-base-value: 0.0
    mobs-base-value: 0.0
    affects-mobs: true
    affects-players: true
  health:
    enabled: true
    format: '%value% Health'
    percentage: false
    players-max-value: 100.0
    mobs-max-value: 100.0
    players-base-value: 20.0
    mobs-base-value: 20.0
    affects-mobs: true
    affects-players: true
  damage:
    enabled: true
    format: '%value% Damage'
    percentage: false
    players-max-value: 100.0
    mobs-max-value: 100.0
    players-base-value: 1.0
    mobs-base-value: 1.0
    affects-mobs: true
    affects-players: true
  block:
    enabled: true
    format: '%value% Block'
    percentage: true
    players-max-value: 100.0
    mobs-max-value: 100.0
    players-base-value: 0.5
    mobs-base-value: 0.0
    affects-mobs: false
    affects-players: true
  armor:
    enabled: true
    format: '%value% Armor'
    percentage: false
    players-max-value: 100.0
    mobs-max-value: 100.0
    players-base-value: 0.0
    mobs-base-value: 0.0
    affects-mobs: true
    affects-players: true
  fire-damage:
    enabled: true
    format: '%value% Fire Damage'
    percentage: false
    players-max-value: 100.0
    mobs-max-value: 100.0
    players-base-value: 0.0
    mobs-base-value: 0.0
    affects-mobs: true
    affects-players: true
  critical-damage:
    enabled: true
    format: '%value% Critical Damage'
    percentage: true
    players-max-value: 100.0
    mobs-max-value: 100.0
    players-base-value: 0.2
    mobs-base-value: 0.0
    affects-mobs: true
    affects-players: true
  permission-requirement:
    enabled: true
    format: 'Permission Requirement: %value%'
    percentage: false
    players-max-value: -1.0
    mobs-max-value: -1.0
    players-base-value: -1.0
    mobs-base-value: -1.0
    affects-mobs: true
    affects-players: true
  stun-rate:
    enabled: true
    format: '%value% Stun Rate'
    percentage: true
    players-max-value: 100.0
    mobs-max-value: 100.0
    players-base-value: 0.05
    mobs-base-value: 0.0
    affects-mobs: true
    affects-players: true
  armor-penetration:
    enabled: true
    format: '%value% Armor Penetration'
    percentage: false
    players-max-value: 100.0
    mobs-max-value: 100.0
    players-base-value: 0.0
    mobs-base-value: 0.0
    affects-mobs: true
    affects-players: true
  parry:
    enabled: true
    format: '%value% Parry'
    percentage: true
    players-max-value: 100.0
    mobs-max-value: 100.0
    players-base-value: 1.5
    mobs-base-value: 0.0
    affects-mobs: false
    affects-players: true
  level-requirement:
    enabled: true
    format: 'Level Requirement: %value%'
    percentage: false
    players-max-value: 100.0
    mobs-max-value: 100.0
    players-base-value: 0.0
    mobs-base-value: 0.0
    affects-mobs: true
    affects-players: true
  stun-length:
    enabled: true
    format: '%value% Stun Length'
    percentage: false
    players-max-value: 100.0
    mobs-max-value: 100.0
    players-base-value: 1.0
    mobs-base-value: 0.0
    affects-mobs: true
    affects-players: true
  wither-immunity:
    enabled: true
    format: Wither Immunity
    percentage: false
    players-max-value: -1.0
    mobs-max-value: -1.0
    players-base-value: -1.0
    mobs-base-value: -1.0
    affects-mobs: true
    affects-players: true