options:
  base-player-health: 20.0
  base-critical-damage: 0.2
  base-critical-rate: 0.05
  base-stun-rate: 0.05
  base-stun-length: 1
  base-dodge-rate: 0.0
  seconds-between-health-updates: 10
core-stats:
  health:
    format: "%value% Health"
  damage:
    format: "%value% Damage"
  melee-damage:
    format: "%value% Melee Damage"
  ranged-damage:
    format: "%value% Ranged Damage"
  regeneration:
    format: "%value% Regeneration"
  armor:
    format: "%value% Armor"
  critical-rate:
    format: "%value% Critical Rate"
    max-value: 100.0
  critical-damage:
    format: "%value% Critical Damage"
    max-value: 100.0
  level-requirement:
    format: "Level Required: %value%"
  armor-penetration:
    format: "%value% Armor Penetration"
  stun-rate:
    format: "%value% Stun Rate"
    max-value: 100.0
  stun-length:
    format: "%value% Stun Length"
  dodge-rate:
    format: "%value% Dodge Rate"
    max-value: 100.0
  fire-immunity:
    format: "Fire Immunity"
  poison-immunity:
    format: "Poison Immunity"
  wither-immunity:
    format: "Wither Immunity"
version: "1.0.9"